on:
  push:

env:
  IMAGE_NAME: korsakjakub/pco-api
    
jobs:
  release-container-image:
    name: Release the container image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get short sha
        id: short-sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '20'
          cache: 'maven'
      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      - name: Build and push the image with jib
        run: mvn compile jib:build -Dimage=${{ env.IMAGE_NAME }}:${{ steps.short-sha.outputs.sha }}

